### PR TITLE
libsbp 2.2.15 & Piksi Multi firmware 1.2

### PR DESCRIPTION
**Pull request by marco-tranzatto**
This pull request introduces:

- usage of libsbp 2.2.15: https://github.com/swift-nav/libsbp/releases/tag/v2.2.15
- relying on latest Piksi Multi Firmware (1.2), i.e. every Piksi Multi must update its firmware;
- RQT GUI now has two tabs: general status and a debug section with more information;
- new message: "age of corrections", to check how old the correction message currently used is;
- draft sbp messages (like TrackingState) now include the sbp version number in their name, so it is clear to which sbp version they belong to and do not need to be deleted when there is a new version of them;
- signal strength "cn0" is now expressed in [dB Hz/4] instead of the previous [dB Hz];
- rosservices now allow to write, read and save firmware settings to flash memory of Piksi Multi;
- 'roslaunch piksi_multi_rtk_gps geodetic_survey.launch' now allows to survey the position of the base station and save the result to Piksi's flash.

### CODE REVIEW

**Comment by kholtmann** [comment]
@marco-tranzatto I extended the gui to include the signal strength units and added the sbp 2.2.15 documentation.

**Comment by marija-p** [comment]
@marco-tranzatto @kholtmann I'm cleaning up old PRs.. what's the status on this?

**Comment by marco-tranzatto** [comment]
@marija-p we are still working on this and probably merge in two weeks, once we can test the latest changes on the robot.

**Comment by marija-p** [comment]
@marco-tranzatto Cool, just checking. :) Thanks! :+1:

**Comment by marco-tranzatto** [comment]
@marija-p  We'll hopefully merge soon. Thanks for cleaning up :+1:

**Pull request merged**
